x = int(input())
y = x % 1000
n = y // 100
print(n)

sec = int(input())
hour = sec // 3600
minute = (sec // 60) - (hour * 60)
second = sec - (hour * 3600) - (minute * 60)
print(hour, minute, second, sep=':')

x = int(input())
print(x % 2)

x, y, N = map(int, input().split())
z = x * N
c = y * N
kop = c % 100
rub = z + (c // 100)
print(f'{rub} руб. {kop} коп.')

N = int(input())
print('(\___/) ' * N)
print("(='.'=) " * N)
print('(")_(") ' * N)

K = input()
N = int(input())
R = int(input())
X = int(K * N)
print(X * R)

print(int(((6.5 * 100) ** 2 + (4.5 * 100) ** 2) ** (1/2)))

import turtle

turtle.speed(1000)
turtle.up()
turtle.pensize(9)
turtle.pencolor("#a8daff")
turtle.forward(110)
turtle.right(90)
turtle.forward(20)
turtle.down()
turtle.forward(88)
turtle.left(90)
turtle.forward(30)
turtle.left(85)
turtle.forward(88)
turtle.left(95)
turtle.forward(77)
turtle.left(95)
turtle.forward(88)
turtle.left(85)
turtle.forward(90)
turtle.left(80)
turtle.forward(30)
turtle.left(100)
turtle.forward(130)
turtle.right(80)
turtle.forward(30)
turtle.right(100)
turtle.forward(140)
turtle.up()
turtle.home()

turtle.color("#286591")
turtle.down()
turtle.forward(30)
turtle.right(80)
turtle.forward(90)
turtle.up()
turtle.left(180)
turtle.forward(70)
turtle.right(100)
turtle.down()
turtle.forward(150)
turtle.right(100)
turtle.forward(90)
turtle.right(80)
turtle.forward(118)
turtle.left(100)
turtle.forward(20)
turtle.left(80)
turtle.forward(110)
turtle.up()

turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(20)
turtle.down()
turtle.begin_fill()
turtle.circle(10)
turtle.up()
turtle.forward(70)
turtle.down()
turtle.circle(10)
turtle.end_fill()

turtle.done()

import turtle

turtle.speed(1000)

turtle.right(180)
turtle.fillcolor("blue")
turtle.pencolor("blue")
turtle.begin_fill()
turtle.circle(100, 20)
turtle.end_fill()
turtle.fillcolor("green")
turtle.pencolor("green")
turtle.begin_fill()
turtle.circle(100, 50)
turtle.end_fill()
turtle.fillcolor("orange")
turtle.pencolor("orange")
turtle.begin_fill()
turtle.circle(100, 70)
turtle.end_fill()
turtle.fillcolor("red")
turtle.pencolor("red")
turtle.begin_fill()
turtle.circle(100, 100)
turtle.end_fill()
turtle.fillcolor("#009eff")
turtle.pencolor("#009eff")
turtle.begin_fill()
turtle.circle(100, 120)
turtle.end_fill()

turtle.pencolor("white")
turtle.pensize(2)
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("red")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(80)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("orange")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(110)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("green")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(130)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor("blue")
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(160)
turtle.forward(100)
turtle.end_fill()

turtle.up()
turtle.setposition(-20, 10)
turtle.pencolor("black")
turtle.write("E",)
turtle.setposition(-80, -20)
turtle.write("D")
turtle.setposition(-110, -130)
turtle.write("C")
turtle.setposition(20, -220)
turtle.write("B")
turtle.setposition(100, -60)
turtle.write("A")

turtle.done()

raw = input('Enter number:')
num = raw
print(num)

import math

a = int(input())
b = int(input())
c = int(input())
cb = math.acos((((c ** 2) + (b ** 2) - (a ** 2)) / (2 * b * c))) * (180 / math.pi)
ab = math.acos((((a ** 2) + (b ** 2) - (c ** 2)) / (2 * b * a))) * (180 / math.pi)
ac = math.acos((((a ** 2) + (c ** 2) - (b ** 2)) / (2 * a * c))) * (180 / math.pi)
print(cb, ab, ac)

ATT = int(input())
COMP = int(input())
YDS = int(input())
TD = int(input())
INT = int(input())
QBR = ((COMP / ATT - 0.3) * 5 + (YDS / ATT - 3) * 0.25 + (TD /ATT) * 20 + 2.375 - (INT / ATT) * 25) * 100 / 6
print(QBR)

X = int(input())
Y = int(input())
print(int(X % Y == 0 or Y % X == 0))

N = float(input())
hour = N / 30
minute = hour * 60
print(int(hour), int(minute))

import datetime

current_date = datetime.date.today().isoformat()
print(current_date)
